### ISSUE TITLE
Ignored field not at the end of the message

### ISSUE THREAD

**Issue by pgarbo** [drewnoakes/dasher#13]
If received message has unexpected field at the beginning or in the middle, it throws Dasher.DeserialisationException "Data stream ended" exception. See the following test:

        public void IgnoresUnexpectedFieldAtTheBeginning()
        {
            var bytes = PackBytes(packer => packer.PackMapHeader(3)
                .Pack("SUPRISE").Pack(987)
                .Pack("Name").Pack("Bob")                
                .Pack("Score").Pack(123));

            var deserialiser = new Deserialiser<UserScore>(UnexpectedFieldBehaviour.Ignore);
            var after = deserialiser.Deserialise(bytes);

            Assert.Equal("Bob", after.Name);
            Assert.Equal(123, after.Score);
        }

If this scenario makes sense to you I can take a look.

**Comment by drewnoakes** [comment]
Fixed in 0.3.1.
