### ISSUE TITLE
Nullable type with default value throws exception

### ISSUE THREAD

**Issue by pgarbo** [drewnoakes/dasher#18]
Nullable type with default value throws `System.Security.VerificationException
Operation could destabilize the runtime.`

    public sealed class NullableDefault
    {
        public NullableDefault(bool? b = null)
        {
            B = b;         
        }
        public bool? B { get; }
    }

**Comment by drewnoakes** [comment]
Fixed in [0.4.3](https://www.nuget.org/packages/Dasher/0.4.3).
