### ISSUE TITLE
Could we use type safety better in the serialiser and deserialiser interfaces?

### ISSUE THREAD

**Issue by andysturrock** [drewnoakes/dasher#9]
Have a look at what I have done in my [generics branch](https://github.com/andysturrock/msgpack-strict/tree/generics).

I think we could use compile time types better with generics, which might lead to better performance (compile-time substitution of types, rather than runtime lookup) and better type safety.

However there are 5 failing tests.
* 2 are for `System.Security.VerificationException : Operation could destabilize the runtime.`
* 3 are for `System.InvalidProgramException : JIT Compiler encountered an internal limitation.`

The first two are probably my mistake.  The other three look less solvable, so maybe we need to wait for the new Roslyn compiler!

**Comment by drewnoakes** [comment]
Hi Andy,

There's practically no performance hit when using the non-generic deserialiser. Internally it just casts `object` to the target type twice -- on the way in, and on the way out. These involve a type check (an integer comparison) and unlikely branch to throw on failure. We are talking a handful of nanoseconds each time you call `Deserialise` and the branch predictor will avoid any CPU pipeline stalling.

The situation your branch would avoid is:

    var ser = StrictSerialiser.Get(typeof(Foo));
    ser.Serialise(new Bar(), stream);           // runtime error

This kind of programmer error is avoided by using the current generic interface:

    var ser = StrictSerialiser.Get<Foo>();
    ser.Serialise(new Bar(), stream);           // compile error

Unfortunately removing the non-generic API means you can't (sensibly) use the serialisers in places where you only know the type at runtime. Serialisation APIs in the .NET framework expose either both, or only the former style for this reason.

Another point on the above changes is that if you switch from `C.M<T>` to `C<T>.M` then you end up with per-generic-type copies of static fields of `C`. So in your branch you wouldn't need the `ConcurrentDictionary` -- a simple static field of type `StrictDeserialiser<T>` would be sufficient if made suitably threadsafe. This PR removes about 50 LOC, and you could remove a little more, but we'd then give up the ability to work with runtime only types.

If you're compiling this solution, then you're already using the new Roslyn compiler! It shipped with VS2015/C#6.

**Comment by andysturrock** [comment]
I might be harking back to my C++ days and being paranoid about runtime type problems rather than compile time.

Oh I didn't realise that Roslyn was in VS2015.  I guess from the error messages that it still has some `internal limitation`s :-)

**Comment by drewnoakes** [comment]
Yeah lots of C++ devs look down on RTTI. In this case the code is generated
for the specific type directly, just as it would be with templates. The
generated code is non-generic. It's just that the interface requires the
type check on the way in and out.

**Comment by andysturrock** [comment]
OK sounds good.
